export const DEFAULT_MOCK_ORDERS = [
  {
    id: 'ORD-2401',
    customer: 'Priya Sharma',
    email: 'priya@email.com',
    amount: 4599,
    status: 'Delivered',
    items: 2,
    date: '2026-06-20',
    products: ['Silk Midi Dress', 'Classic White Tee'],
    lineItems: [
      { name: 'Silk Midi Dress', variant: 'M / Red', qty: 1, price: 3200 },
      { name: 'Classic White Tee', variant: 'L / White', qty: 1, price: 1180 },
    ],
  },
  {
    id: 'ORD-2402',
    customer: 'Arjun Mehta',
    email: 'arjun@email.com',
    amount: 12999,
    status: 'Shipped',
    items: 1,
    date: '2026-06-21',
    products: ['Tailored Charcoal Suit'],
    lineItems: [
      { name: 'Tailored Charcoal Suit', variant: '42 / Charcoal', qty: 1, price: 12380 },
    ],
  },
  {
    id: 'ORD-2403',
    customer: 'Sneha Reddy',
    email: 'sneha@email.com',
    amount: 3499,
    status: 'Processing',
    items: 3,
    date: '2026-06-22',
    products: ['Relaxed Linen Camp Shirt', 'Slim Fit Denim', 'Urban Runner Sneakers'],
    lineItems: [
      { name: 'Relaxed Linen Camp Shirt', variant: 'M / Blue', qty: 1, price: 1100 },
      { name: 'Slim Fit Denim', variant: '32 / Indigo', qty: 1, price: 1300 },
      { name: 'Urban Runner Sneakers', variant: '9 / White', qty: 1, price: 932 },
    ],
  },
  {
    id: 'ORD-2404',
    customer: 'Rahul Kapoor',
    email: 'rahul@email.com',
    amount: 8999,
    status: 'Pending',
    items: 1,
    date: '2026-06-23',
    products: ['3D Formal Blazer'],
    lineItems: [{ name: '3D Formal Blazer', variant: 'L / Navy', qty: 1, price: 8570 }],
  },
  {
    id: 'ORD-2405',
    customer: 'Ananya Iyer',
    email: 'ananya@email.com',
    amount: 5999,
    status: 'Processing',
    items: 2,
    date: '2026-06-24',
    products: ['3D Utility Field Jacket', 'Premium Fleece Hoodie'],
    lineItems: [
      { name: '3D Utility Field Jacket', variant: 'XL / Olive', qty: 1, price: 3200 },
      { name: 'Premium Fleece Hoodie', variant: 'M / Grey', qty: 1, price: 2514 },
    ],
  },
  {
    id: 'ORD-2406',
    customer: 'Vikram Singh',
    email: 'vikram@email.com',
    amount: 2499,
    status: 'Cancelled',
    items: 1,
    date: '2026-06-25',
    products: ['Classic White Tee'],
    lineItems: [{ name: 'Classic White Tee', variant: 'S / Black', qty: 1, price: 2380 }],
  },
];

export const DEFAULT_SUPPORT_TICKETS = [
  {
    id: 'TKT-101',
    user: 'Vikram Singh',
    email: 'vikram@email.com',
    subject: 'AI image not loading in Virtual Fitting Room',
    message:
      'When I click Run AI Fitting, the preview stays blank after 2 minutes. Face Studio body scan works fine.',
    status: 'Open',
    adminReply: '',
    userUnread: false,
    createdAt: '2026-06-25',
  },
  {
    id: 'TKT-102',
    user: 'Meera Patel',
    email: 'meera@email.com',
    subject: 'Try-on result looks pixelated',
    message: 'The IDM-VTON output is very low resolution on mobile Safari.',
    status: 'Open',
    adminReply: '',
    userUnread: false,
    createdAt: '2026-06-24',
  },
  {
    id: 'TKT-103',
    user: 'Guest #8821',
    email: 'guest8821@temp.mail',
    subject: 'Cannot save look to closet',
    message: 'Save Look button does nothing after successful AI try-on.',
    status: 'Answered',
    adminReply:
      'Please ensure you completed a real AI fit (not dev pairing). We pushed a fix — retry after refresh.',
    userUnread: false,
    createdAt: '2026-06-22',
  },
];
