const DEFAULT_TITLE = 'My 3D AI Wardrobe Look';
const DEFAULT_TEXT = 'Check out my new look generated by AI!';
const PINTEREST_DESCRIPTION = 'My AI Wardrobe Look';

export function getShareUrl() {
  if (typeof window === 'undefined') return '';
  return window.location.href;
}

export function buildSharePayload(product) {
  const productName = product?.name?.trim();
  const text = productName ? `${DEFAULT_TEXT} — ${productName}` : DEFAULT_TEXT;

  return {
    title: DEFAULT_TITLE,
    text,
    url: getShareUrl(),
  };
}

export function getWhatsAppShareUrl(url, text = DEFAULT_TEXT) {
  const message = `${text} ${url}`.trim();
  return `https://api.whatsapp.com/send?text=${encodeURIComponent(message)}`;
}

export function getFacebookShareUrl(url) {
  return `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`;
}

export function getPinterestShareUrl(url, description = PINTEREST_DESCRIPTION) {
  const params = new URLSearchParams({
    url,
    description,
  });
  return `https://pinterest.com/pin/create/button/?${params.toString()}`;
}

/**
 * Prefer native OS share sheet (mobile). Opens fallback UI when Web Share is unavailable.
 */
export async function triggerNativeShare(product, { onFallback } = {}) {
  const shareData = buildSharePayload(product);

  if (typeof navigator !== 'undefined' && navigator.share) {
    try {
      await navigator.share({
        title: shareData.title,
        text: shareData.text,
        url: shareData.url,
      });
      return { method: 'native' };
    } catch (error) {
      if (error?.name === 'AbortError') {
        return { method: 'cancelled' };
      }
      console.error('Share failed', error);
    }
  }

  onFallback?.();
  return { method: 'fallback' };
}

export async function copyShareLink(url) {
  if (typeof navigator === 'undefined' || !navigator.clipboard?.writeText) {
    throw new Error('Clipboard is not available in this browser.');
  }
  await navigator.clipboard.writeText(url);
}
